config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "callbacks"}
  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  root 'welcome#home'

  resources :lists, only: [:show, :index, :edit, :update, :destroy, :new]
  resources :lists do 
    resources :categories, only: [:new, :update]
    resources :items, only: [:show, :new, :edit, :update, :destroy, :patch, :post, :create]
  end
  resources :list, only: [:new, :show, :edit, :update, :destroy]
  resources :items, only: [:show, :new, :edit, :update, :destroy, :patch, :post]
  


  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :lists
    has_many :users, through: :lists  
    validates :name, presence: true
    validates_uniqueness_of :name

    
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list
    validates :description, presence: true
    
end

app/models/list.rb
class List < ApplicationRecord

    belongs_to :user
    belongs_to :category
    has_many :items
    accepts_nested_attributes_for :category, reject_if: :all_blank 
    validates :name, presence: true
    scope :sort_list, -> { List.order(description: :desc) }

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :lists 
  has_many :categories, through: :lists
  accepts_nested_attributes_for :lists

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.name = auth.info.name
      user.uid = auth.uid 
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    before_action :authenticate_user!

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController 
    def github 
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end 

end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController

    def create 
        @category = Category.create(params[:name])
        self.update(category)
    end



    private

    def catagory_params
        params.require(:category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :current_list, only: [:new, :create]
    before_action :current_item,  only: [:show, :destroy]

    def new 
        current_list
        @item = @list.items.build
    end

    def create 
        current_list
        @item = @list.items.create(item_params)
        if  @item.save
            redirect_to list_path(@list)
        else 
            render "items/new"
        end
    end

    def show  
        current_item
    end

    def destroy
        current_item
        @list = @item.list_id
        @item.destroy
        redirect_to list_path(@list)
    end

    private 

    def item_params
        params.require(:item).permit(:description, :checked_off)
    end

    def current_list
        @list = current_user.lists.find_by_id(params[:list_id])
    end

    def current_item
        @item = Item.find_by(id: params[:id])
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :require_permission, only: :show 
    
    def index 
        @user = current_user
        @lists = @user.lists.sort_list
    end
    
    def new
        @list = current_user.lists.build
    end
    
    def create 
        @list = current_user.lists.build(list_params)
        if @list.save
            redirect_to list_path(@list)
        else
            render 'new'
        end
    end
    
    def edit 
        @list = current_user.lists.find_by(id: params[:id])
    end
    
    def update 
        if  current_user != List.find(params[:id]).user 
            redirect_to root_path
        else
            @list = current_user.lists.find_by(id: params[:id])
            if @list.update(list_params)
                redirect_to list_path(@list)
            else 
                render 'edit'
            end
        end
    end
    
    def show 
        @list = current_user.lists.find_by_id(params[:id])
        @items = @list.items
    end
    
    def destroy
         if  current_user != List.find(params[:id]).user 
             redirect_to root_path
         else
            @list = current_user.lists.find_by(id: params[:id])
            @list.destroy
            redirect_to lists_path
         end
    end
    
    private 

    def require_permission
        if current_user != List.find(params[:id]).user
            redirect_to lists_path
        end
        rescue ActiveRecord::RecordNotFound
        redirect_to root_url, :flash => { :error => "Record not found." }
    end
    
    def list_params 
        params.require(:list).permit(:user_id, :name, :category_id, :description, category_attributes: [
            :name
        ])
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


    private 
    
    def signup_params 
        params.require(:user).permit( :name,
                                      :email,
                                      :password,
                                      :password_confirmation)
    end

    def account_update_params 
        params.require(:user).permit(  :name, 
                                       :email,
                                       :password,
                                       :password_confirmation,
                                       :current_password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/new.html.erb
<% if !@item.errors.messages.empty? %>
    <div id="error_explanation">
        <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end%>
    </div>
<% end %>
<h3>Add Item</h3>

<%= form_for [@list, @item] do |f| %>
    <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
    </p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/items/show.html.erb
<%= @item.description %>

<%= link_to "Delete", @item, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListProject</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% if false %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag :defaults %>
    <% end %>

  </head>

  <body>
  <% if user_signed_in? %>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/">List Builder</a>
      <form class="form-inline">
        <a class="btn btn-outline-primary" href="\lists" role="button">
        Lists
        </a>
        <div style="padding-left: 10px;">
        <a class="btn btn-outline-success" role="button"<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </a>
        </div>
      </form>
    </nav>
    <% else %>
      <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/">List Builder</a>
      <form class="form-inline">
        <a class="btn btn-outline-primary" href="\users\sign_in" role="button">
        Login
        </a>
        <div style="padding-left: 10px;">
          <a class="btn btn-outline-success" href="\users\sign_up" role="button">
          Sign Up
          </a>
        </div>
        <div style="padding-left: 10px;">
        <a class="btn btn-outline-success" role="button"<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </a>
        </div>
      </form>
    </nav>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<% if !@list.errors.messages.empty? %>
    <div id="error_explanation">
        <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end%>
    </div>
<% end %>

<%= form_for @list do |f| %>

    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>
    <P>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
    </p>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
    <%= f.fields_for :category, @list.build_category do |cat| %>
        <p>
        <%= cat.label :name %>
        <%= cat.text_field :name%>
        </p>
    <% end %>

    <p>
    <%= f.submit %>
    </p>

<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= render partial: 'form', locals: {user: @list} %>

app/views/lists/index.html.erb
<h1>Lists<h2>
<table>
<p><%= link_to "New List", new_list_path %></p><br>



<% @lists.each do |l| %>
    <tr>
    <p>
    <%= link_to "#{l.name}", list_path(l) %>
    <p>Category: <%= l.category.name %></p>
    <p>Description: <%= l.description %></p>
    <%= link_to "Delete List", l, method: :delete %>
    </p><br><br>
    </tr>
</table>
<% end %>


app/views/lists/new.html.erb
<h1>Create A List</h1>
<%= render partial: 'form', locals: {user: @list} %>

app/views/lists/show.html.erb

<%= @list.name %><br>
<%= @list.description %>
<br>

<p>


<% @items.each do |i| %>
    <h3><%= link_to i.description, list_item_path(@list, i) %></h3>
<% end %>
</p>





<%= link_to 'New Item',  new_list_item_path(@list) %><br>
<%= link_to 'Edit List',  edit_list_path(@list) %>





app/views/welcome/home.html.erb

<h1 style="text-align:center">Welcome to the List Builder</h1>
<h2 style="text-align:center">You can create list for any type of catagory by using this app</h2>